name: Deploy admin Staging

on:
  push:
    branches:
      - staging
      - feat/workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: copy env
        run: |
          echo "NEXT_PUBLIC_BASE_URL=https://api.loyalty-point.stagingtekita.it.com/" >> .env
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:stg-${{ github.sha }} .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:stg-${{ github.sha }}
      
      